name: Build and Deploy Full-Stack Application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # Build and test the React frontend
  build-frontend:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: server/frontend/package.json
        
    - name: Install frontend dependencies
      run: |
        cd server/frontend
        npm install
        
    - name: Build React application
      run: |
        cd server/frontend
        CI=false npm run build
        
    - name: Upload frontend build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: frontend-build
        path: server/frontend/build/
        
  # Build and test the Django backend
  build-backend:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install Python dependencies
      run: |
        cd server
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run Django tests
      run: |
        cd server
        python manage.py test
        
    - name: Collect static files
      run: |
        cd server
        python manage.py collectstatic --noinput
        
    - name: Upload backend artifacts
      uses: actions/upload-artifact@v4
      with:
        name: backend-build
        path: server/
        
  # Build Node.js microservices
  build-microservices:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install database service dependencies
      run: |
        cd server/database
        npm install
        
    - name: Test database services
      run: |
        cd server/database
        npm test || echo "No tests specified"
        
    - name: Upload microservices artifacts
      uses: actions/upload-artifact@v4
      with:
        name: microservices-build
        path: server/database/
        
  # Deploy to GitHub Pages (Frontend only)
  deploy-frontend:
    needs: [build-frontend, build-backend, build-microservices]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    permissions:
      contents: read
      pages: write
      id-token: write
      
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
      
    steps:
    - name: Download frontend build
      uses: actions/download-artifact@v4
      with:
        name: frontend-build
        path: ./build
        
    - name: Setup Pages
      uses: actions/configure-pages@v4
      
    - name: Upload to GitHub Pages
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./build
        
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4

  # Optional: Build Docker images for containerized deployment
  build-docker:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Build and push database service
      uses: docker/build-push-action@v5
      with:
        context: ./server/database
        push: true
        tags: ghcr.io/ireneusrdx/xrwvm-fullstack-developer-capstone-database:latest
        
    - name: Build and push Django backend
      uses: docker/build-push-action@v5
      with:
        context: ./server
        file: ./server/Dockerfile
        push: true
        tags: ghcr.io/ireneusrdx/xrwvm-fullstack-developer-capstone-backend:latest
